# tasks for touchegg role

- name: Installing touchegg
  package:
    name: touchegg

- name: Installing touchegg config
  copy:
    src:  touchegg.conf
    dest: ~/.config/touchegg/touchegg.conf
    mode: "0644"

- name: Enabling touchegg service
  service:
    name:    touchegg
    state:   started
    enabled: true

- name: Installing touche
  become: false
  community.general.flatpak:
    name:   com.github.joseexposito.touche
    method: system

