# tasks for cockpit role

- name: Installing cockpit packages
  package:
    name:
      - cockpit
      - cockpit-machines
      - cockpit-podman
      - cockpit-pcp

- name: Starting cockpit.socket
  service:
    name:    "{{ item }}"
    state:   started
    enabled: true
  loop:
    - cockpit.socket
    - podman.service
    - pmlogger.service

