# tasks for sudo role

- name: Adding admin user to wheel group
  user:
    name:   "{{ admin_user }}"
    groups: wheel
    append: true

- name: Setting passwordless sudo for wheel group
  copy:
    src:  wheel
    dest: /etc/sudoers.d/wheel
    mode: "0600"

