#!/bin/sh
#
# Show zypper history
#
# Put this file into /usr/lib/zypper/commands/
# Call as zypper history

cut                        \
  --fields 1-4             \
  --delimiter '|'          \
  --only-delimited         \
  --output-delimiter ' | ' \
  /var/log/zypp/history    \
| grep -v ' radd '         \
| column -t -s '|'

